#pragma once
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_1 	guess-numbers
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_2 	deep-dark-fraction
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_3 	programmable-robot
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_4 	broken-board-dominoes
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_5 	coin-bonus
#define SOLUTION_CPP_FOLDER_NAME_ID_1	two-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_2 	add-two-numbers
#define SOLUTION_CPP_FOLDER_NAME_ID_11 	container-with-most-water
#define SOLUTION_CPP_FOLDER_NAME_ID_13 	roman-to-integer
#define SOLUTION_CPP_FOLDER_NAME_ID_14 	longest-common-prefix
#define SOLUTION_CPP_FOLDER_NAME_ID_15 	3sum
#define SOLUTION_CPP_FOLDER_NAME_ID_16 	3sum-closest
#define SOLUTION_CPP_FOLDER_NAME_ID_17 	letter-combinations-of-a-phone-number
#define SOLUTION_CPP_FOLDER_NAME_ID_18 	4sum
#define SOLUTION_CPP_FOLDER_NAME_ID_19 	remove-nth-node-from-end-of-list
#define SOLUTION_CPP_FOLDER_NAME_ID_20 	valid-parentheses
#define SOLUTION_CPP_FOLDER_NAME_ID_21 	merge-two-sorted-lists
#define SOLUTION_CPP_FOLDER_NAME_ID_101 	symmetric-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_102 	binary-tree-level-order-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_103 	binary-tree-zigzag-level-order-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_104 	maximum-depth-of-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_105 	construct-binary-tree-from-preorder-and-inorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_106 	construct-binary-tree-from-inorder-and-postorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_107 	binary-tree-level-order-traversal-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_108 	convert-sorted-array-to-binary-search-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_110 	balanced-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_111 	minimum-depth-of-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_112 	path-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_118 	pascals-triangle
#define SOLUTION_CPP_FOLDER_NAME_ID_119 	pascals-triangle-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_120 	triangle
#define SOLUTION_CPP_FOLDER_NAME_ID_121 	best-time-to-buy-and-sell-stock
#define SOLUTION_CPP_FOLDER_NAME_ID_122 	best-time-to-buy-and-sell-stock-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_124 	binary-tree-maximum-path-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_125 	valid-palindrome
#define SOLUTION_CPP_FOLDER_NAME_ID_128 	longest-consecutive-sequence
#define SOLUTION_CPP_FOLDER_NAME_ID_130 	surrounded-regions
#define SOLUTION_CPP_FOLDER_NAME_ID_134 	gas-station
#define SOLUTION_CPP_FOLDER_NAME_ID_136 	single-number
#define SOLUTION_CPP_FOLDER_NAME_ID_144 	binary-tree-preorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_145 	binary-tree-postorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_148 	sort-list
#define SOLUTION_CPP_FOLDER_NAME_ID_149 	max-points-on-a-line
#define SOLUTION_CPP_FOLDER_NAME_ID_150 	evaluate-reverse-polish-notation
#define SOLUTION_CPP_FOLDER_NAME_ID_151 	reverse-words-in-a-string
#define SOLUTION_CPP_FOLDER_NAME_ID_152 	maximum-product-subarray
#define SOLUTION_CPP_FOLDER_NAME_ID_153 	find-minimum-in-rotated-sorted-array
#define SOLUTION_CPP_FOLDER_NAME_ID_154 	find-minimum-in-rotated-sorted-array-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_162 	find-peak-element
#define SOLUTION_CPP_FOLDER_NAME_ID_166 	fraction-to-recurring-decimal
#define SOLUTION_CPP_FOLDER_NAME_ID_167 	two-sum-ii-input-array-is-sorted
#define SOLUTION_CPP_FOLDER_NAME_ID_169 	majority-element
#define SOLUTION_CPP_FOLDER_NAME_ID_171 	excel-sheet-column-number
#define SOLUTION_CPP_FOLDER_NAME_ID_172 	factorial-trailing-zeroes
#define SOLUTION_CPP_FOLDER_NAME_ID_179 	largest-number
#define SOLUTION_CPP_FOLDER_NAME_ID_189 	rotate-array
#define SOLUTION_CPP_FOLDER_NAME_ID_189 	rotate-array
#define SOLUTION_CPP_FOLDER_NAME_ID_190 	reverse-bits
#define SOLUTION_CPP_FOLDER_NAME_ID_191 	number-of-1-bits
#define SOLUTION_CPP_FOLDER_NAME_ID_198 	house-robber
#define SOLUTION_CPP_FOLDER_NAME_ID_200 	number-of-islands
#define SOLUTION_CPP_FOLDER_NAME_ID_202 	happy-number
#define SOLUTION_CPP_FOLDER_NAME_ID_203 	remove-linked-list-elements
#define SOLUTION_CPP_FOLDER_NAME_ID_204 	count-primes
#define SOLUTION_CPP_FOLDER_NAME_ID_205 	isomorphic-strings
#define SOLUTION_CPP_FOLDER_NAME_ID_206 	reverse-linked-list
#define SOLUTION_CPP_FOLDER_NAME_ID_209 	minimum-size-subarray-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_213 	house-robber-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_215 	kth-largest-element-in-an-array
#define SOLUTION_CPP_FOLDER_NAME_ID_1207 	unique-number-of-occurrences
#define SOLUTION_CPP_FOLDER_NAME_ID_1208 	get-equal-substrings-within-budget
#define SOLUTION_CPP_FOLDER_NAME_ID_1209 	remove-all-adjacent-duplicates-in-string-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_1210 	minimum-moves-to-reach-target-with-rotations
#define SOLUTION_CPP_FOLDER_NAME_ID_1221 	split-a-string-in-balanced-strings
#define SOLUTION_CPP_FOLDER_NAME_ID_1222 	queens-that-can-attack-the-king
#define SOLUTION_CPP_FOLDER_NAME_ID_1223 	dice-roll-simulation
#define SOLUTION_CPP_FOLDER_NAME_ID_1224 	maximum-equal-frequency
#define SOLUTION_CPP_FOLDER_NAME_ID_1228 	missing-number-in-arithmetic-progression
#define SOLUTION_CPP_FOLDER_NAME_ID_1229 	meeting-scheduler
#define SOLUTION_CPP_FOLDER_NAME_ID_1230 	toss-strange-coins
#define SOLUTION_CPP_FOLDER_NAME_ID_1231 	divide-chocolate
#define SOLUTION_CPP_FOLDER_NAME_ID_1232 	check-if-it-is-a-straight-line
#define SOLUTION_CPP_FOLDER_NAME_ID_1233 	remove-sub-folders-from-the-filesystem
#define SOLUTION_CPP_FOLDER_NAME_ID_1234 	replace-the-substring-for-balanced-string
#define SOLUTION_CPP_FOLDER_NAME_ID_1235 	maximum-profit-in-job-scheduling
#define SOLUTION_CPP_FOLDER_NAME_ID_5238 	find-positive-integer-solution-for-a-given-equation
#define SOLUTION_CPP_FOLDER_NAME_ID_5239 	circular-permutation-in-binary-representation
#define SOLUTION_CPP_FOLDER_NAME_ID_5240 	maximum-length-of-a-concatenated-string-with-unique-characters
#define SOLUTION_CPP_FOLDER_NAME_ID_5241 	tiling-a-rectangle-with-the-fewest-squares
