#pragma once
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_1 	guess-numbers
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_2 	deep-dark-fraction
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_3 	programmable-robot
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_4 	broken-board-dominoes
#define SOLUTION_CPP_FOLDER_NAME_ID_LCP_5 	coin-bonus
#define SOLUTION_CPP_FOLDER_NAME_ID_TEST_0	_test_0
#define SOLUTION_CPP_FOLDER_NAME_ID_1	two-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_2 	add-two-numbers
#define SOLUTION_CPP_FOLDER_NAME_ID_3 	longest-substring-without-repeating-characters
#define SOLUTION_CPP_FOLDER_NAME_ID_4 	median-of-two-sorted-arrays
#define SOLUTION_CPP_FOLDER_NAME_ID_11 	container-with-most-water
#define SOLUTION_CPP_FOLDER_NAME_ID_13 	roman-to-integer
#define SOLUTION_CPP_FOLDER_NAME_ID_14 	longest-common-prefix
#define SOLUTION_CPP_FOLDER_NAME_ID_15 	3sum
#define SOLUTION_CPP_FOLDER_NAME_ID_16 	3sum-closest
#define SOLUTION_CPP_FOLDER_NAME_ID_17 	letter-combinations-of-a-phone-number
#define SOLUTION_CPP_FOLDER_NAME_ID_18 	4sum
#define SOLUTION_CPP_FOLDER_NAME_ID_19 	remove-nth-node-from-end-of-list
#define SOLUTION_CPP_FOLDER_NAME_ID_20 	valid-parentheses
#define SOLUTION_CPP_FOLDER_NAME_ID_21 	merge-two-sorted-lists
#define SOLUTION_CPP_FOLDER_NAME_ID_22 	generate-parentheses
#define SOLUTION_CPP_FOLDER_NAME_ID_24 	swap-nodes-in-pairs
#define SOLUTION_CPP_FOLDER_NAME_ID_26 	remove-duplicates-from-sorted-array
#define SOLUTION_CPP_FOLDER_NAME_ID_27 	remove-element
#define SOLUTION_CPP_FOLDER_NAME_ID_28 	implement-strstr
#define SOLUTION_CPP_FOLDER_NAME_ID_29 	divide-two-integers
#define SOLUTION_CPP_FOLDER_NAME_ID_31 	next-permutation
#define SOLUTION_CPP_FOLDER_NAME_ID_33 	search-in-rotated-sorted-array
#define SOLUTION_CPP_FOLDER_NAME_ID_34 	find-first-and-last-position-of-element-in-sorted-array
#define SOLUTION_CPP_FOLDER_NAME_ID_35 	search-insert-position
#define SOLUTION_CPP_FOLDER_NAME_ID_36 	valid-sudoku
#define SOLUTION_CPP_FOLDER_NAME_ID_38 	count-and-say
#define SOLUTION_CPP_FOLDER_NAME_ID_41 	first-missing-positive
#define SOLUTION_CPP_FOLDER_NAME_ID_42 	trapping-rain-water
#define SOLUTION_CPP_FOLDER_NAME_ID_43 	multiply-strings
#define SOLUTION_CPP_FOLDER_NAME_ID_45 	jump-game-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_101 	symmetric-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_102 	binary-tree-level-order-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_103 	binary-tree-zigzag-level-order-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_104 	maximum-depth-of-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_105 	construct-binary-tree-from-preorder-and-inorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_106 	construct-binary-tree-from-inorder-and-postorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_107 	binary-tree-level-order-traversal-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_108 	convert-sorted-array-to-binary-search-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_110 	balanced-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_111 	minimum-depth-of-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_112 	path-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_118 	pascals-triangle
#define SOLUTION_CPP_FOLDER_NAME_ID_119 	pascals-triangle-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_120 	triangle
#define SOLUTION_CPP_FOLDER_NAME_ID_121 	best-time-to-buy-and-sell-stock
#define SOLUTION_CPP_FOLDER_NAME_ID_122 	best-time-to-buy-and-sell-stock-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_124 	binary-tree-maximum-path-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_125 	valid-palindrome
#define SOLUTION_CPP_FOLDER_NAME_ID_128 	longest-consecutive-sequence
#define SOLUTION_CPP_FOLDER_NAME_ID_130 	surrounded-regions
#define SOLUTION_CPP_FOLDER_NAME_ID_134 	gas-station
#define SOLUTION_CPP_FOLDER_NAME_ID_136 	single-number
#define SOLUTION_CPP_FOLDER_NAME_ID_144 	binary-tree-preorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_145 	binary-tree-postorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_148 	sort-list
#define SOLUTION_CPP_FOLDER_NAME_ID_149 	max-points-on-a-line
#define SOLUTION_CPP_FOLDER_NAME_ID_150 	evaluate-reverse-polish-notation
#define SOLUTION_CPP_FOLDER_NAME_ID_151 	reverse-words-in-a-string
#define SOLUTION_CPP_FOLDER_NAME_ID_152 	maximum-product-subarray
#define SOLUTION_CPP_FOLDER_NAME_ID_153 	find-minimum-in-rotated-sorted-array
#define SOLUTION_CPP_FOLDER_NAME_ID_154 	find-minimum-in-rotated-sorted-array-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_162 	find-peak-element
#define SOLUTION_CPP_FOLDER_NAME_ID_166 	fraction-to-recurring-decimal
#define SOLUTION_CPP_FOLDER_NAME_ID_167 	two-sum-ii-input-array-is-sorted
#define SOLUTION_CPP_FOLDER_NAME_ID_169 	majority-element
#define SOLUTION_CPP_FOLDER_NAME_ID_171 	excel-sheet-column-number
#define SOLUTION_CPP_FOLDER_NAME_ID_172 	factorial-trailing-zeroes
#define SOLUTION_CPP_FOLDER_NAME_ID_179 	largest-number
#define SOLUTION_CPP_FOLDER_NAME_ID_189 	rotate-array
#define SOLUTION_CPP_FOLDER_NAME_ID_189 	rotate-array
#define SOLUTION_CPP_FOLDER_NAME_ID_190 	reverse-bits
#define SOLUTION_CPP_FOLDER_NAME_ID_191 	number-of-1-bits
#define SOLUTION_CPP_FOLDER_NAME_ID_198 	house-robber
#define SOLUTION_CPP_FOLDER_NAME_ID_200 	number-of-islands
#define SOLUTION_CPP_FOLDER_NAME_ID_202 	happy-number
#define SOLUTION_CPP_FOLDER_NAME_ID_203 	remove-linked-list-elements
#define SOLUTION_CPP_FOLDER_NAME_ID_204 	count-primes
#define SOLUTION_CPP_FOLDER_NAME_ID_205 	isomorphic-strings
#define SOLUTION_CPP_FOLDER_NAME_ID_206 	reverse-linked-list
#define SOLUTION_CPP_FOLDER_NAME_ID_209 	minimum-size-subarray-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_213 	house-robber-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_215 	kth-largest-element-in-an-array
#define SOLUTION_CPP_FOLDER_NAME_ID_217 	contains-duplicate
#define SOLUTION_CPP_FOLDER_NAME_ID_218 	the-skyline-problem
#define SOLUTION_CPP_FOLDER_NAME_ID_219 	contains-duplicate-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_220 	contains-duplicate-iii
#define SOLUTION_CPP_FOLDER_NAME_ID_221 	maximal-square
#define SOLUTION_CPP_FOLDER_NAME_ID_222 	count-complete-tree-nodes
#define SOLUTION_CPP_FOLDER_NAME_ID_226 	invert-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_227 	basic-calculator-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_230 	kth-smallest-element-in-a-bst
#define SOLUTION_CPP_FOLDER_NAME_ID_231 	power-of-two
#define SOLUTION_CPP_FOLDER_NAME_ID_234 	palindrome-linked-list
#define SOLUTION_CPP_FOLDER_NAME_ID_235 	lowest-common-ancestor-of-a-binary-search-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_236 	lowest-common-ancestor-of-a-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_237 	delete-node-in-a-linked-list
#define SOLUTION_CPP_FOLDER_NAME_ID_238 	product-of-array-except-self
#define SOLUTION_CPP_FOLDER_NAME_ID_239 	sliding-window-maximum
#define SOLUTION_CPP_FOLDER_NAME_ID_240 	search-a-2d-matrix-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_242 	valid-anagram
#define SOLUTION_CPP_FOLDER_NAME_ID_257 	binary-tree-paths
#define SOLUTION_CPP_FOLDER_NAME_ID_268 	missing-number
#define SOLUTION_CPP_FOLDER_NAME_ID_278 	first-bad-version
#define SOLUTION_CPP_FOLDER_NAME_ID_279 	perfect-squares
#define SOLUTION_CPP_FOLDER_NAME_ID_283 	move-zeroes
#define SOLUTION_CPP_FOLDER_NAME_ID_287 	find-the-duplicate-number
#define SOLUTION_CPP_FOLDER_NAME_ID_289 	game-of-life
#define SOLUTION_CPP_FOLDER_NAME_ID_290 	word-pattern
#define SOLUTION_CPP_FOLDER_NAME_ID_292 	nim-game
#define SOLUTION_CPP_FOLDER_NAME_ID_300 	longest-increasing-subsequence
#define SOLUTION_CPP_FOLDER_NAME_ID_303 	range-sum-query-immutable
#define SOLUTION_CPP_FOLDER_NAME_ID_304 	range-sum-query-2d-immutable
#define SOLUTION_CPP_FOLDER_NAME_ID_315 	count-of-smaller-numbers-after-self
#define SOLUTION_CPP_FOLDER_NAME_ID_322 	coin-change
#define SOLUTION_CPP_FOLDER_NAME_ID_324 	wiggle-sort-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_326 	power-of-three
#define SOLUTION_CPP_FOLDER_NAME_ID_328 	odd-even-linked-list
#define SOLUTION_CPP_FOLDER_NAME_ID_334 	increasing-triplet-subsequence
#define SOLUTION_CPP_FOLDER_NAME_ID_337 	house-robber-iii
#define SOLUTION_CPP_FOLDER_NAME_ID_344 	reverse-string
#define SOLUTION_CPP_FOLDER_NAME_ID_345 	reverse-vowels-of-a-string
#define SOLUTION_CPP_FOLDER_NAME_ID_347 	top-k-frequent-elements
#define SOLUTION_CPP_FOLDER_NAME_ID_349 	intersection-of-two-arrays
#define SOLUTION_CPP_FOLDER_NAME_ID_350 	intersection-of-two-arrays-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_354 	russian-doll-envelopes
#define SOLUTION_CPP_FOLDER_NAME_ID_367 	valid-perfect-square
#define SOLUTION_CPP_FOLDER_NAME_ID_371 	sum-of-two-integers
#define SOLUTION_CPP_FOLDER_NAME_ID_374 	guess-number-higher-or-lower
#define SOLUTION_CPP_FOLDER_NAME_ID_378 	kth-smallest-element-in-a-sorted-matrix
#define SOLUTION_CPP_FOLDER_NAME_ID_387 	first-unique-character-in-a-string
#define SOLUTION_CPP_FOLDER_NAME_ID_390 	elimination-game
#define SOLUTION_CPP_FOLDER_NAME_ID_393 	utf-8-validation
#define SOLUTION_CPP_FOLDER_NAME_ID_394 	decode-string
#define SOLUTION_CPP_FOLDER_NAME_ID_395 	longest-substring-with-at-least-k-repeating-characters
#define SOLUTION_CPP_FOLDER_NAME_ID_410 	split-array-largest-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_412 	fizz-buzz
#define SOLUTION_CPP_FOLDER_NAME_ID_415 	add-strings
#define SOLUTION_CPP_FOLDER_NAME_ID_416 	partition-equal-subset-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_447 	number-of-boomerangs
#define SOLUTION_CPP_FOLDER_NAME_ID_541 	reverse-string-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_541 	reverse-string-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_1207 	unique-number-of-occurrences
#define SOLUTION_CPP_FOLDER_NAME_ID_1208 	get-equal-substrings-within-budget
#define SOLUTION_CPP_FOLDER_NAME_ID_1209 	remove-all-adjacent-duplicates-in-string-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_1210 	minimum-moves-to-reach-target-with-rotations
#define SOLUTION_CPP_FOLDER_NAME_ID_1217 	play-with-chips
#define SOLUTION_CPP_FOLDER_NAME_ID_1218 	longest-arithmetic-subsequence-of-given-difference
#define SOLUTION_CPP_FOLDER_NAME_ID_1219 	path-with-maximum-gold
#define SOLUTION_CPP_FOLDER_NAME_ID_1220 	count-vowels-permutation
#define SOLUTION_CPP_FOLDER_NAME_ID_1221 	split-a-string-in-balanced-strings
#define SOLUTION_CPP_FOLDER_NAME_ID_1222 	queens-that-can-attack-the-king
#define SOLUTION_CPP_FOLDER_NAME_ID_1223 	dice-roll-simulation
#define SOLUTION_CPP_FOLDER_NAME_ID_1224 	maximum-equal-frequency
#define SOLUTION_CPP_FOLDER_NAME_ID_1228 	missing-number-in-arithmetic-progression
#define SOLUTION_CPP_FOLDER_NAME_ID_1229 	meeting-scheduler
#define SOLUTION_CPP_FOLDER_NAME_ID_1230 	toss-strange-coins
#define SOLUTION_CPP_FOLDER_NAME_ID_1231 	divide-chocolate
#define SOLUTION_CPP_FOLDER_NAME_ID_1232 	check-if-it-is-a-straight-line
#define SOLUTION_CPP_FOLDER_NAME_ID_1233 	remove-sub-folders-from-the-filesystem
#define SOLUTION_CPP_FOLDER_NAME_ID_1234 	replace-the-substring-for-balanced-string
#define SOLUTION_CPP_FOLDER_NAME_ID_1235 	maximum-profit-in-job-scheduling
#define SOLUTION_CPP_FOLDER_NAME_ID_1243 	array-transformation
#define SOLUTION_CPP_FOLDER_NAME_ID_1244 	design-a-leaderboard
#define SOLUTION_CPP_FOLDER_NAME_ID_1245 	tree-diameter
#define SOLUTION_CPP_FOLDER_NAME_ID_1246 	palindrome-removal
#define SOLUTION_CPP_FOLDER_NAME_ID_1237 	find-positive-integer-solution-for-a-given-equation
#define SOLUTION_CPP_FOLDER_NAME_ID_1238 	circular-permutation-in-binary-representation
#define SOLUTION_CPP_FOLDER_NAME_ID_1239 	maximum-length-of-a-concatenated-string-with-unique-characters
#define SOLUTION_CPP_FOLDER_NAME_ID_1240 	tiling-a-rectangle-with-the-fewest-squares
#define SOLUTION_CPP_FOLDER_NAME_ID_1247 	minimum-swaps-to-make-strings-equal
#define SOLUTION_CPP_FOLDER_NAME_ID_1248 	count-number-of-nice-subarrays
#define SOLUTION_CPP_FOLDER_NAME_ID_1249 	minimum-remove-to-make-valid-parentheses
#define SOLUTION_CPP_FOLDER_NAME_ID_1250 	check-if-it-is-a-good-array
#define SOLUTION_CPP_FOLDER_NAME_ID_5255 	cells-with-odd-values-in-a-matrix
#define SOLUTION_CPP_FOLDER_NAME_ID_5256 	reconstruct-a-2-row-binary-matrix
#define SOLUTION_CPP_FOLDER_NAME_ID_5257 	number-of-closed-islands
#define SOLUTION_CPP_FOLDER_NAME_ID_5258 	maximum-score-words-formed-by-letters
