#pragma once
#define SOLUTION_CPP_FOLDER_NAME_ID_1	two-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_11 	container-with-most-water
#define SOLUTION_CPP_FOLDER_NAME_ID_13 	roman-to-integer
#define SOLUTION_CPP_FOLDER_NAME_ID_14 	longest-common-prefix
#define SOLUTION_CPP_FOLDER_NAME_ID_15 	3sum
#define SOLUTION_CPP_FOLDER_NAME_ID_101 	symmetric-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_102 	binary-tree-level-order-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_103 	binary-tree-zigzag-level-order-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_104 	maximum-depth-of-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_105 	construct-binary-tree-from-preorder-and-inorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_106 	construct-binary-tree-from-inorder-and-postorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_107 	binary-tree-level-order-traversal-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_108 	convert-sorted-array-to-binary-search-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_110 	balanced-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_111 	minimum-depth-of-binary-tree
#define SOLUTION_CPP_FOLDER_NAME_ID_112 	path-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_118 	pascals-triangle
#define SOLUTION_CPP_FOLDER_NAME_ID_119 	pascals-triangle-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_120 	triangle
#define SOLUTION_CPP_FOLDER_NAME_ID_121 	best-time-to-buy-and-sell-stock
#define SOLUTION_CPP_FOLDER_NAME_ID_122 	best-time-to-buy-and-sell-stock-ii
#define SOLUTION_CPP_FOLDER_NAME_ID_124 	binary-tree-maximum-path-sum
#define SOLUTION_CPP_FOLDER_NAME_ID_125 	valid-palindrome
#define SOLUTION_CPP_FOLDER_NAME_ID_128 	longest-consecutive-sequence
#define SOLUTION_CPP_FOLDER_NAME_ID_130 	surrounded-regions
#define SOLUTION_CPP_FOLDER_NAME_ID_134 	gas-station
#define SOLUTION_CPP_FOLDER_NAME_ID_136 	single-number
#define SOLUTION_CPP_FOLDER_NAME_ID_144 	binary-tree-preorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_145 	binary-tree-postorder-traversal
#define SOLUTION_CPP_FOLDER_NAME_ID_148 	sort-list
#define SOLUTION_CPP_FOLDER_NAME_ID_149 	max-points-on-a-line
